### ISSUE TITLE
启动应用后，点击‘用例管理’模块提示错误！

### ISSUE THREAD

**Issue by Duchongc** [testdevhome/Autotestplat#2]
![image](https://user-images.githubusercontent.com/31360737/47206994-aa57e700-d3bc-11e8-8134-be3c4d9dcdf1.png)

**Comment by yang1997yi** [comment]
请问大佬login页面的用户名密码是什么 或者怎么加进数据库，非常感谢

**Comment by HEhunter** [comment]
没有提供数据库表，所以代码开源也没什么用

**Comment by testdevhome** [comment]
书里有详细写的
